clc;
clear all;
b = input('Enter the numerator coefficients: ');
a = input('Enter the denominator coefficients: ');
[h,w] = freqz(b,a);
subplot(3,1,1);
plot(w/pi,abs(h));
grid;
xlabel('Normalised Frequency');
ylabel('Magnitude in dB');
title('Magnitude Response-Ishan Grover-102219028');
subplot(3,1,2);
plot(w/pi,angle(h));
grid;
xlabel('Normalised Frequency');
ylabel('Phase in Radians');
title('Phase Response-Ishan Grover-102219028');
subplot(3,1,3);
zplane(b,a);